Desktop version
Dadadon/Setup-and-mobile-version-skeleton pull request #5
Opened 2021-08-26 18:55 UTC by Dadadon

- Used media queries in my CSS file to make desktop version look like the template I selected.

- Lay out the elements on the page using Grid and Flexbox.

2021-08-26 21:25 UTC, barackm requested changes
Hi @Dadadon, 👋 

You have done an amazing job so far! 👏👏👏
However, there are some issues that you still need to work on to go to the next project. But remember you are almost there 😉  😉 !

# STATUS: Required Changes ♻️
### _Check the comments under the review._ 👇 
![](https://media.giphy.com/media/iZKF7CKpEEva2OZE6a/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] [OPTIONAL] Commit messages should be descriptive to give an idea of changes that have been introduced, but I have noticed that almost all your commit messages are the same, for example, `Update style.css` has been repeated 10 times in your commit messages, This can not help you easily understand the changes you have introduced at a later time. Let's make better mistakes tomorrow 😉 

- [ ] [OPTIONAL] I have seen that you have added all your images to the root of the project, this is not good, we should organize our files, for example, you can create a folder called `images` where you could keep all the images 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-26 21:25 UTC, barackm commented on style.css
> -@media all and (max-width: 375px) {
- [ ] Since we are using the `mobile-first` approach we should not add the media queries for the mobile version, because by default the styling should be responsible for the mobile version only, and then we should add the media queries only for tablet or desktop versions 😉

2021-08-26 21:25 UTC, barackm commented on style.css
> +@media all and (min-width: 1440px) {
- [ ] This is great to take `1440px` for the desktop version since it is in the range of `992px` - `1100px`, however, your desktop version doesn't seem to work. See screenshot below 👇 
![image](https://user-images.githubusercontent.com/55465133/131036444-1507ed1b-992e-4ec3-82c3-7876b54e7c16.png)

Can you please fix this issue?

2021-08-26 21:25 UTC, barackm commented on style.css
> -body {
- [ ] It seems that while working on your desktop version you have broken your mobile version, see the difference below 👇 
- Before

![image](https://user-images.githubusercontent.com/55465133/131037131-711290b9-257a-4fcd-82f6-c6135b934342.png)
![image](https://user-images.githubusercontent.com/55465133/131037268-cdfc8c00-fb19-43fe-8adc-c1ed3e93e7f9.png)

- Now

![image](https://user-images.githubusercontent.com/55465133/131037085-4dc598e4-3ffc-442d-b1dd-173d1689ec39.png)
![image](https://user-images.githubusercontent.com/55465133/131037220-0db05c73-d0bf-4a5c-876d-7e90a9f46396.png)

While working on the desktop version we should not touch the code we had before for the mobile version, since it's only for the mobile version, the only code that can be changed is what we have inside the media queries in the range of `992px` - `1100px`, with this, the code for the mobile version can not be affected while you are working on the desktop or tablet version, Kindly let's fix this issue 👍

2021-08-26 21:25 UTC, barackm commented on index.html
>      <div class="grid-container2">
- [ ] It seems that even this section has a problem in the desktop version like all the other sections, see the screenshots below
![image](https://user-images.githubusercontent.com/55465133/131037996-10f9da18-a302-42c9-a906-71386410ca15.png)

Please let's fix our media queries 😉

2021-08-27 08:04 UTC, Dadadon commented on style.css
> -@media all and (max-width: 375px) {
I don't understand. Isn't the website responsive? Media queries allow me to do just that

2021-08-27 08:05 UTC, Dadadon commented on style.css
> +@media all and (min-width: 1440px) {
The template had a width of 1440px. Weren't we supposed to replicate that?

2021-08-27 08:06 UTC, Dadadon commented on style.css
> -body {
This issue has been fixed

2021-08-27 08:06 UTC, Dadadon commented on index.html
>      <div class="grid-container2">
I don't understand

2021-08-27 08:16 UTC, barackm commented on style.css
> +@media all and (min-width: 1440px) {
Hi @Dadadon, what I mean here is that your media queries do not affect the design yet, because as you can see above 👆  the Desktop version doesn't seem to be styled yet. and it could be better to use instead the range of 992px - 1100px for the desktop screens 👍

2021-08-27 08:37 UTC, barackm commented on style.css
> -@media all and (max-width: 375px) {
Yeah, sure the media queries allow you to make your website responsive 👍 , but what is going on here is that you have started to work on the mobile version of your portfolio (mobile-first) approach, which means without media queries the website should be responsive for the mobile version, so we can only have media queries for other screen sizes like tablet and desktop(should be in the range of `992px` - `1100px`), you can learn more about the mobile-first approach [here](https://smartbear.com/learn/performance-monitoring/what-is-mobile-first/#:~:text=Mobile%20First%20Approach%20refers%20to,the%20design%20for%20mobile%20afterwards.)

2021-08-27 14:00 UTC, Dadadon commented on style.css
> -@media all and (max-width: 375px) {
Oh I understand now thanks

2021-08-27 14:00 UTC, Dadadon commented on style.css
> +@media all and (min-width: 1440px) {
Oh okay

2021-08-28 06:34 UTC, DanteAlonsoHT approved these changes
<h1>Status: Approve 🥇 ✔</h1>
Hi @Dadadon, 

### Please, check the consideration (in the comments below) to improve your project before merging it :shipit: 😉 
## Congratulations! 🎉 

### Cheers and Keep the good work!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="100%">

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-28 06:34 UTC, DanteAlonsoHT commented on index.html
> +            </button>
- [ ] [OPTIONAL] For all you button, you can consider to add the next CSS styles to improve the UX in your website.

```
button:hover {
  cursor: pointer;
}
```

2021-08-28 06:34 UTC, DanteAlonsoHT commented on index.html
> +                <p class="p-textd">A daily selection of privately personalized reads; no accounts or sign-ups required.</p>
I love your design for your dekstop version due to it doesn't matter if you are in a large or medium screen for all desktops your design is responsive, but your mobile design can be better if you add styles to make it more responsive for different mobile screen sizes,

- [ ] [OPTIONAL] Improve the responsive design for your mobile version.

![image](https://user-images.githubusercontent.com/60164239/131208698-79e55033-3711-4030-9425-20437c1624e9.png)

2021-08-28 06:42 UTC, merged